ex03pronto
studas/SCC0604-POO-2022.2 pull request #29
Opened 2022-10-09 16:28 UTC by GuScarenci

O exerício 03 da lista 04 era simplesmente responder uma pergunta teórica fácil. Criei um .txt com o enunciado e a resposta.

2022-10-09 19:44 UTC, cirillom commented on lista04/lista04ex03/ex03.txt
> +Um bloco try e catch pode contar vários "catches" pois um bloco de código pode gerar mais de um tipo de exceção. Então se você deseja pegar diferentes tipos de exceções, você deve usar diferentes "ca
Correção de digitação
E acho que seria daora explicar o porque "ArithmeticException" deve vir antes de "Exception"

```suggestion
Um bloco try e catch pode contar vários "catches" pois um bloco de código pode gerar mais de um tipo de exceção. Então se você deseja pegar diferentes tipos de exceções, você deve usar diferentes "catches". Os blocos de catch devem ser odenados do mais específico para o mais geral na hierarquia das exceções. Por exemplo: o "catch" de "ArithmeticException" deve vir antes do "catch" para "Exception", pois "ArithmeticException" é lançado para o erro especifico de divisão por 0, e "Exception" é lançado para um erro desconhecido, portanto deve estar abaixo do erro conhecido (divisão por 0).Lembrando que só é possível acontecer uma exceção por vez e apenas um bloco "catch" será executado.
```

2022-10-09 19:45 UTC, cirillom requested changes
Resposta boa no geral, mas tem erros de digitação e melhorias na explicação

2022-10-10 00:31 UTC, CarlosCraveiro approved these changes
Resposta muito boa

2022-10-10 00:41 UTC, cirillom approved these changes

2022-10-10 01:26 UTC, merged